### ISSUE TITLE
Error: Error: connect ECONNREFUSED 127.0.0.1:3000

### ISSUE THREAD

**Issue by clackes** [rastvl/akamai-deobfuscator-2.0#1]
This is all error, and sensor data isn't valid, some tips for where to start to correct it?

```
    at Object.dispatchError (C:\Users\Flackoss\Desktop\akamai-deobfuscator-2.0-main\akamai-deobfuscator-2.0-main\node_modules\jsdom\lib\jsdom\living\xhr\xhr-utils.js:63:19)     
    at Request.<anonymous> (C:\Users\Flackoss\Desktop\akamai-deobfuscator-2.0-main\akamai-deobfuscator-2.0-main\node_modules\jsdom\lib\jsdom\living\xhr\XMLHttpRequest-impl.js:655:18)
    at Request.emit (node:events:525:35)
    at ClientRequest.<anonymous> (C:\Users\Flackoss\Desktop\akamai-deobfuscator-2.0-main\akamai-deobfuscator-2.0-main\node_modules\jsdom\lib\jsdom\living\helpers\http-request.js:127:14)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:481:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) undefined
Error: Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object.dispatchError (C:\Users\Flackoss\Desktop\akamai-deobfuscator-2.0-main\akamai-deobfuscator-2.0-main\node_modules\jsdom\lib\jsdom\living\xhr\xhr-utils.js:63:19)     
    at Request.<anonymous> (C:\Users\Flackoss\Desktop\akamai-deobfuscator-2.0-main\akamai-deobfuscator-2.0-main\node_modules\jsdom\lib\jsdom\living\xhr\XMLHttpRequest-impl.js:655:18)
    at Request.emit (node:events:525:35)
    at ClientRequest.<anonymous> (C:\Users\Flackoss\Desktop\akamai-deobfuscator-2.0-main\akamai-deobfuscator-2.0-main\node_modules\jsdom\lib\jsdom\living\helpers\http-request.js:127:14)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:481:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) undefined
Error: Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object.dispatchError (C:\Users\Flackoss\Desktop\akamai-deobfuscator-2.0-main\akamai-deobfuscator-2.0-main\node_modules\jsdom\lib\jsdom\living\xhr\xhr-utils.js:63:19)     
    at Request.<anonymous> (C:\Users\Flackoss\Desktop\akamai-deobfuscator-2.0-main\akamai-deobfuscator-2.0-main\node_modules\jsdom\lib\jsdom\living\xhr\XMLHttpRequest-impl.js:655:18)
    at Request.emit (node:events:525:35)
    at ClientRequest.<anonymous> (C:\Users\Flackoss\Desktop\akamai-deobfuscator-2.0-main\akamai-deobfuscator-2.0-main\node_modules\jsdom\lib\jsdom\living\helpers\http-request.js:127:14)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:481:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) undefined
Error: Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object.dispatchError (C:\Users\Flackoss\Desktop\akamai-deobfuscator-2.0-main\akamai-deobfuscator-2.0-main\node_modules\jsdom\lib\jsdom\living\xhr\xhr-utils.js:63:19)     
    at Request.<anonymous> (C:\Users\Flackoss\Desktop\akamai-deobfuscator-2.0-main\akamai-deobfuscator-2.0-main\node_modules\jsdom\lib\jsdom\living\xhr\XMLHttpRequest-impl.js:655:18)
    at Request.emit (node:events:525:35)
    at ClientRequest.<anonymous> (C:\Users\Flackoss\Desktop\akamai-deobfuscator-2.0-main\akamai-deobfuscator-2.0-main\node_modules\jsdom\lib\jsdom\living\helpers\http-request.js:127:14)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:481:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) undefined```

**Comment by yvvki** [comment]
> This is all error, and sensor data isn't valid, some tips for where to start to correct it?

Seems like you have not start the server via `node ./utils/server.js` as mentioned in the README.

**Comment by shuaibibobo** [comment]
![屏幕截图(16)](https://github.com/rastvl/akamai-deobfuscator-2.0/assets/22990695/2de1e8bd-3aaa-4fef-ac69-ce2b9a28e548)
